config/routes.rb
Rails.application.routes.draw do
    root 'students#index'


    get "/students", to: "students#index"
    resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

  validates :first_name, length: { maximum: 40 }, presence: true
  validates :middle_name, length: { maximum: 60 }, presence: false
  validates :last_name, length: { maximum: 40 }, presence: true
  validates :sex, presence: true
  enum sex: ["male", "female"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [ :show, :edit, :update, :destroy ]
  helper_method :sort_col, :sort_direction

  def index
    @students = Student.order( sort_col + ' ' + sort_direction )
    @student = Student.new
  end
  
  def new
    @student = Student.new
  end

  def show
  end

  def edit
    
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
        format.js
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :bad_request}
        format.js
      end
    end
  end
  
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :bad_request}
        format.js
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :middle_name, :last_name, :sex, :nick_name)
  end

 def sort_col
   Student.column_names.include?( params[ :sort ] ) ? params[ :sort ] : "last_name"
 end

 def sort_direction
   %w[ asc desc ].include?( params[ :direction ] ) ? params[ :direction ] : "asc"
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    fasort = sort_direction == "asc" ? "down" : "up" 
    css_class = column == sort_col ? "current" : nil
    direction = column == sort_col && sort_direction == "asc" ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'vue-script', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
   <div class="alert alert-error">
     The form contains <%= pluralize(object.errors.count, "error") %>.
   </div>
  <ul>
   <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/students/_form.html.erb
        <%= simple_form_for @student, remote: true, :html => { class: "form-group row"} do |f| %>
          <%= f.input :first_name, label_html: { class: 'col-sm-2 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_first_name' } %>
          <%= f.input :middle_name, label_html: { class: 'col-sm-2 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_middle_name' } %>
          <%= f.input :last_name, label_html: { class: 'col-sm-2 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_last_name' }%>
          <%= f.input :nick_name , label_html: { class: 'col-sm-2 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_nick_name' }%>
          <%= f.input :sex, as: :radio_buttons, collection: [['male', 'male'], ['female', 'female']], label_method: :second, value_method: :first, wrapper_html: { class: 'student_sex' } %>
      </div>
      <div class="modal-footer">
          <%= link_to 'cancel', students_path, class: "btn btn-warning" %>
          <%= f.button :submit, class: "btn btn-primary" %>
      </div>
        <% end %>

app/views/students/_student.html.erb
<tr id="student_<%= student.id %>">
      <th scope="row"></th>
      <td>
        <%= student.first_name =%>
      </td>
      <td>
        <%= student.middle_name %>
      </td>
      <td>
        <button type="button" class="btn btn-link" data-toggle="modal" data-target="#updatestudent_<%= student.id %>">
        <%= student.last_name %>
      </td>
      <td>
        <%= student.sex%>
      </td>
      <td>
        <%= student.nick_name %>
      </td>
      <td>
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#updatestudent_<%= student.id %>">
          Edit
        </button>
        <%=  link_to 'Destroy', student, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger" %>
      </td>
</tr>
<!-- Modal -->
<div class="modal fade bd-example-modal-lg"  id="updatestudent_<%= student.id %>" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalTitle">Update student</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(student, remote: true, :html => { class: "form-group row"}) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.input :first_name, label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_first_name' } %>
          <%= f.input :middle_name, label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_middle_name' } %>
          <%= f.input :last_name, label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_last_name' }%>
          <%= f.input :nick_name , label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_nick_name' }%>
          <%= f.input :sex, as: :radio_buttons, collection: [['male', 'male'], ['female', 'female']], label_method: :second, value_method: :first, input_html: { class: 'form-control' }, label_html: { class: "col-form-label" }, wrapper_html: { class: 'col-sm-4 student_sex' } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary"%>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/students/create.js.erb
<% if @student.save %>
      $("#editStudents").modal('hide');
      location.reload();
<% end %>

app/views/students/edit.html.erb
<h3>Edit student</h3>

<%= render 'form' %>

app/views/students/index.html.erb
<!-- Button trigger modal -->
<br />
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editStudents">
 New Students 
</button>
<div class ="row" 
<h3>Students</h3> 
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">
        <%= sortable "first_name", "First"%>
      </th>
      <th scope="col">
        <%= sortable "middle_name", "Middle" %>
      </th>
      <th scope="col">
        <%= sortable "last_name", "Last"%>
      </th>
      <th scope="col">
        <%= sortable "sex", "Gender"%>
      </th>
      <th scope="col">
        <%= sortable "nick_name", "Nick"%>
      </th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody id="students_tbody">
      <%= render @students %>
  </tbody>
 </table>
</div>
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="editStudents" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalTitle">Add new student</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @student, remote: true, :html => { class: "form-group row"} do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.input :first_name, label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_first_name' } %>
          <%= f.input :middle_name, label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_middle_name' } %>
          <%= f.input :last_name, label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_last_name' }%>
          <%= f.input :nick_name , label_html: { class: 'col-sm-4 col-form-label' }, input_html: { class: 'form-control' }, wrapper_html: { class: 'col-sm-10 student_nick_name' }%>
          <%= f.input :sex, as: :radio_buttons, collection: [['male', 'male'], ['female', 'female']], label_method: :second, value_method: :first, input_html: { class: 'form-control' }, label_html: { class: "col-form-label" }, wrapper_html: { class: 'col-sm-4 student_sex' } %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary" %>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/students/update.js.erb
<% if @student.save %>
  $("#updatestudent_<%= @student.id %>").modal('hide');
<% end %>